export default () => ({
  orders: [],
  orderListeners: [],
  jobTaskListeners: [],
  taskReportListeners: [],
  playNotification: false,
  showOrderNotification: false,
  taskRequirementListeners: [],
  taskMaterialsOrToolsListeners: [],
  taskChatUnsubscribe: [],
  showJobNotesDrawerOos: false,
  showPropertyHistoryDrawerOos: false,
  showTaskInfoDrawer: true,
  showTask: false,
  showTaskChats: false,
  hightlightTaskChat: null,
  taskSelected: null,
  openEditOrder: false,
  scrollChatZone: false,
  reportsSelected: [],
  statusOrders: {},
  statusOrderUnsubscribe: [],
  requirementsListMap: [],
  requirementsUnsuscribeMap: {},
})
