export default () => ({
  routes: [],
  filter: null,
  baseOrders: [],
  forDateStr: '',
  markers: [],
  map: null,
  orderSelected: null,
  listeners: [],
  google: null,
  savingRoutes: false,
  routeSelected: null,
  showRouteInMap: false,
  dummyRoute: {
    active: true,
    originLocation: { lat: 40.755664200841004, lng: -74.149279748704 },
    originAddress: '65 Davis Ave, Kearny, NJ 07032, USA',
    forDateStr: '',
    stops: [
      // {num: 0, orders: [], address: ''}
    ],
    orders: [],
    assignedTo: {},
    contractors: [],
    instructions: '',
    files: [],
    rowFiles: [],
    groupName: null,
    createdAt: null,
    updatedAt: null,
    oosSupervisors: [],
    notification: false,
  },
})
