export default () => ({
  allOrders: [],
  allOrdersListeners: [],
  orderProperties: [],
  ordersSelected: [],

  listUrl: [],
  headersDefault: [
    {
      text: 'wo#',
      value: 'woNumber',
      width: '10%',
      align: 'left',
      sortable: true,
    },
    {
      text: 'duedate',
      value: 'dateDueFormatted',
      width: '15%',
      align: 'center',
      cellClass: ['min-width-large'],
      sortable: true,
    },
    {
      text: 'address',
      value: 'address',
      width: '5%',
      align: 'left',
      cellClass: ['truncate'],
      sortable: true,
    },
    {
      text: 'city',
      value: 'city',
      width: '15%',
      align: 'left',
      cellClass: ['min-width-small'],
      sortable: true,
    },
    {
      text: 'zip',
      value: 'zip',
      width: '15%',
      align: 'center',
      cellClass: ['min-width'],
      sortable: true,
    },
    {
      text: 'worktype',
      value: 'workType',
      width: '10%',
      align: 'left',
      cellClass: ['truncate'],
      sortable: true,
    },
    {
      text: 'contractors',
      value: 'contractorList',
      cellClass: ['min-width, truncate'],
      align: 'left',
      sortable: true,
    },
    {
      text: 'status',
      value: 'status',
      width: '10%',
      align: 'center',
      cellClass: ['truncate'],
      sortable: true,
    },
  ],
  filtersDefault: {
    assigned: false,
    archive: false,
    unassigned: false,
    address: '',
    city: '',
    state: '',
    customer: '',
    client: '',
    county: '',
    zip: '',
    workType: '',
    woNumber: '',
    category: '',
    contractor: null,
    status: ['In Field', 'Ready for office', 'Inactive'],
  },
  search: '',
})
