export default () => ({
  order: null,
  loadingOrder: true,
  unsubscribeOrder: null,
  unsubscribeInstructions: null,
  instructions: [],
  allowablesPools: [],
  allowablesPoolsUnsubscribe: null,
  allowables: [],
  allowablesUnsubscribe: null,
  workToDos: [],
  unsubscribeWorkToDos: null,
  appointments: [],
  unsubscribeAppointments: null,
  showOrderGeneralInfo: true,
  taskSelected: null,
  taskReports: [],
  taskReportListener: null,
  unsubscribeInspections: null,
  inspections: [],
})
